# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdatPatient',
            new_name='DeletePatient',
        ),
        migrations.RenameModel(
            old_name='DeleteDoctor',
            new_name='UpdatePatient',
        ),
    ]
