# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0002_auto_20171021_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
